### ISSUE TITLE
Plugin crashes with JSON parse error sometimes

### ISSUE THREAD

**Issue by phansch** [ashfurrow/danger-rubocop#12]
Hey, first of all thanks for the plugin, it has been working perfectly for me in the last few months!
Since a few days unfortunately I sometimes get the following error with this plugin.

```
sh: 1: Syntax error: "(" unexpected
[!] The exception involves the following plugins:
 -  danger-rubocop
bundler: failed to load command: danger (/home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/bin/danger)
Danger::DSLError: 

[!] Invalid `Dangerfile` file: A JSON text must at least contain two octets!
 #  from Dangerfile:38
 #  -------------------------------------------
 #  
 >  rubocop.lint
 #  -------------------------------------------
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-rubocop-0.4.0/lib/danger_plugin.rb:45:in `rubocop'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-rubocop-0.4.0/lib/danger_plugin.rb:37:in `offending_files'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-rubocop-0.4.0/lib/danger_plugin.rb:30:in `lint'
  Dangerfile:38:in `block in parse'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/danger_core/executor.rb:27:in `run'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/lib/danger/commands/runner.rb:66:in `run'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/gems/danger-4.3.3/bin/danger:5:in `<top (required)>'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/bin/danger:23:in `load'
  /home/travis/build/<snip>/vendor/bundle/ruby/2.3.0/bin/danger:23:in `<top (required)>'
```

Unfortunately I'm not 100% sure how to reproduce the error and I don't have much time right now, so I am just opening this issue.
I guess this could be caused by #11, if `rubocop_output` is empty for some reason? I will try to reproduce the error later today and maybe get some more information :sparkles:

**Comment by ashfurrow** [comment]
Hmm, really interesting. That could be it. I don't have a tonne of time this week to investigate, so any help you could provide would be welcome :bow:

**Comment by phansch** [comment]
I managed to find the cause, and I hope to have a PR ready in the next days. The issue is caused by files that contain parentheses or whitespace (As the `sh: 1: Syntax error: "(" unexpected` said).

**Comment by ashfurrow** [comment]
That would be lovely, thanks :bow: No rush!
