### ISSUE TITLE
Error with inline_comment on Ruby 3

### ISSUE THREAD

**Issue by otherguy** [ashfurrow/danger-rubocop#55]
I just ran into this issue when using `danger-rubocop` like this:

`rubocop.lint inline_comment: true`

```
$ bundle exec danger --verbose --fail-if-no-pr=true

bundler: failed to load command: danger (/home/circleci/project/vendor/bundle/ruby/3.0.0/bin/danger)
/home/circleci/project/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/parser/base.rb:92:in `adapt_source': undefined method `valid_encoding?' for {:file=>"Dangerfile", :line=>235}:Hash (NoMethodError)
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/parser/kramdown.rb:90:in `parse'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm.rb:56:in `parse'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/parser/base.rb:69:in `parse'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/document.rb:102:in `initialize'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:14:in `new'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:14:in `markdown_parser'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:51:in `process_markdown'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:59:in `block in table'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:59:in `map'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:59:in `table'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/helpers/comments_helper.rb:98:in `generate_comment'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/request_sources/github/github.rb:192:in `update_pull_request!'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:264:in `post_results'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:292:in `run'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/danger_core/executor.rb:29:in `run'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/lib/danger/commands/runner.rb:73:in `run'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/danger-8.3.1/bin/danger:5:in `<top (required)>'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/bin/danger:23:in `load'
	from /home/circleci/project/vendor/bundle/ruby/3.0.0/bin/danger:23:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'

Exited with code exit status 1
CircleCI received exit code 1
```

I'm using

```
Using danger-rubocop 0.9.5
Using danger 8.3.1
Using rubocop-rails 2.12.2
Using rubocop-rspec 2.5.0
Using rubocop 1.22.1
```

It works with Ruby 2.x so this made me think maybe a splat operator is causing issues on Ruby 3.

**Comment by otherguy** [comment]
The error is `undefined method `valid_encoding?' for {:file=>"Dangerfile", :line=>235}:Hash (NoMethodError)`.

`valid_encoding?` is a String method, but Danger is getting a Hash from `danger-rubocop` in a place where it expects a String.

I assume this is happening [here](https://github.com/ashfurrow/danger-rubocop/blob/master/lib/danger_plugin.rb#L142).

**Comment by otherguy** [comment]
@ashfurrow I hope work is less busy by now :) 

Anyway, I just ran into this issue again when upgrading another project to Ruby 3.

**Comment by hekki** [comment]
@otherguy 
Nice to meet you.

#56 has fixed this issue.
Please use danger-rubocop version `0.10.1` to check if the problem has been fixed in your environment.

**Comment by otherguy** [comment]
Hey @hekki! Thank you so much for taking a look at this!

Unfortunately, it seems, `0.10.1` has not been published yet:

```
Could not find gem 'danger-rubocop (~> 0.10.1)' in rubygems repository https://rubygems.org/ or installed locally.
The source contains the following versions of 'danger-rubocop': 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5
```

**Comment by ashfurrow** [comment]
My apologies there. This comment is a mistake:

https://github.com/ashfurrow/danger-rubocop/pull/56#issuecomment-1053724795

The actual release is `0.10.0`. Sorry for the confusion!

**Comment by otherguy** [comment]
@ashfurrow I did see the release, but 0.9.5 is the latest version on Gemfury.

https://rubygems.org/gems/danger-rubocop/versions/

**Comment by ashfurrow** [comment]
Ahhh yeah, `0.10.0` should be available now: https://rubygems.org/gems/danger-rubocop/versions/0.10.0

**Comment by otherguy** [comment]
Amazing, thank you 🙏

**Comment by ashfurrow** [comment]
Happy to help, but @hekki was the one who actually fixed this ❤️
